# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target ‘taxi’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'DITranquillity'
  pod 'RxAlamofire'
  pod 'ObjectMapper'
  pod 'CodableAlamofire'
  pod 'SwiftHash'
  pod 'Localize-Swift'
  pod 'SVProgressHUD'
  pod 'MapsAPI'
  pod 'GoogleMaps'

  # Pods for taxi

  target 'taxiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'taxiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
